import { createClient } from "@sanity/client";
import * as dotenv from "dotenv";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Load environment variables from studio/.env
dotenv.config({ path: join(__dirname, "../.env") });

const client = createClient({
    projectId: process.env.SANITY_STUDIO_PROJECT_ID,
    dataset: process.env.SANITY_STUDIO_DATASET || "production",
    useCdn: false,
    token: process.env.SANITY_API_TOKEN,
    apiVersion: "2024-02-25",
});

const services = [
    {
        name: "Agentic AI Integration",
        slug: "agentic-ai-integration",
        description: "Seamlessly integrate autonomous agents into your workflow to automate complex decision-making processes.",
        menuDescription: "Autonomous agents for complex workflows",
        heroTitle: "Agentic AI Integration",
        heroSubtitle: ["Transforming workflows with autonomous intelligence."],
        heroTagline: "Next-Gen Automation",
        featuresTitle: "Why Choose Agentic AI?",
        featuresSubtitle: "Our agents are designed to handle high-stakes environments with precision.",
        features: [
            { title: "Autonomous Decision Making", description: "Agents can evaluate multiple variables and choose the best course of action without human intervention.", icon: "Cpu" },
            { title: "Universal Integration", description: "Plugs directly into your existing software stack via API or RPA.", icon: "Layers" },
            { title: "24/7 Operation", description: "Intelligent workers that never sleep, ensuring consistent throughput around the clock.", icon: "Clock" },
            { title: "Adaptive Learning", description: "Self-improving systems that optimize their performance based on feedback loops.", icon: "Zap" },
            { title: "Secure Infrastructure", description: "Built with enterprise-grade security protocols to protect sensitive data.", icon: "Shield" }
        ],
        problemTitle: "The Productivity Gap",
        problemSubtitle: "Traditional automation is rigid. Modern business requires adaptability.",
        problemItems: [
            { title: "Legacy Systems Bottlenecks", description: "Siloed data and manual processes slowing down growth." },
            { title: "Complex Decision Costs", description: "High human overhead for repetitive yet complex analytical tasks." },
            { title: "Slow Velocity", description: "Projects stalled by waiting on manual approvals and handoffs." },
            { title: "Human Error", description: "Costly mistakes slipping through due to fatigue and complexity." }
        ],
        processTitle: "Our Integration Process",
        processSubtitle: "A structured path to agentic excellence.",
        processSteps: [
            { stepId: "01", title: "Discovery", description: "We analyze your current workflows to identify the highest ROI automation opportunities." },
            { stepId: "02", title: "Architecture", description: "Designing a custom agentic framework tailored to your data environment." },
            { stepId: "03", title: "Development", description: "Building and training AI agents with your proprietary data and business logic." },
            { stepId: "04", title: "Integration", description: "Connecting agents to your existing systems via APIs, webhooks, and RPA bridges." },
            { stepId: "05", title: "Deployment", description: "Phased rollout with continuous monitoring and fine-tuning for production readiness." },
            { stepId: "06", title: "Support", description: "Ongoing maintenance, performance optimization, and agent evolution as your needs grow." }
        ],
        ctaTitle: "Ready to Integrate Agentic AI?",
        ctaSubtitle: "Let our team design an autonomous agent strategy tailored to your enterprise.",
        ctaButtonText: "Start Integration",
        ctaButtonLink: "/contact"
    },
    {
        name: "Enterprise Strategy",
        slug: "enterprise-strategy",
        description: "Tailored AI roadmaps designed to align with your business goals and drive long-term digital transformation.",
        menuDescription: "Strategic AI roadmaps for business growth",
        heroTitle: "Enterprise Strategy",
        heroSubtitle: ["Strategic planning for AI-driven excellence."],
        heroTagline: "Strategic Advisory",
        featuresTitle: "Strategic Foundations",
        featuresSubtitle: "Building the AI future of your organization on solid ground.",
        features: [
            { title: "ROI-Focused Roadmapping", description: "Prioritizing AI initiatives that deliver measurable business value.", icon: "TrendingUp" },
            { title: "Risk Mitigation", description: "Proactive identification and management of AI implementation risks.", icon: "ShieldAlert" },
            { title: "Change Management", description: "Preparing your workforce for the transition to AI-augmented workflows.", icon: "Users" },
            { title: "Governance Models", description: "Establishing ethical and operational guidelines for AI use.", icon: "Scale" },
            { title: "Technology Selection", description: "Expert guidance on selecting the right LLMs and platforms.", icon: "Search" }
        ],
        problemTitle: "Directionless AI Adoption",
        problemSubtitle: "Without a strategy, AI projects often become expensive experiments.",
        problemItems: [
            { title: "Fragmented Innovation", description: "Different departments testing different tools with no unified vision." },
            { title: "Compliance Risks", description: "Deploying AI without proper legal or ethical guardrails." },
            { title: "Resource Waste", description: "Budget spent on pilot projects that never reach production." },
            { title: "Skill Gaps", description: "Teams lacking expertise to manage and scale AI initiatives." }
        ],
        processTitle: "The Strategic Journey",
        processSubtitle: "From vision to execution.",
        processSteps: [
            { stepId: "01", title: "Audit", description: "Comprehensive review of your current tech landscape, data maturity, and business objectives." },
            { stepId: "02", title: "Strategy", description: "Development of a 24-month AI transformation roadmap aligned with your business priorities." },
            { stepId: "03", title: "Governance", description: "Setting up ethical guidelines, compliance frameworks, and organizational structures." },
            { stepId: "04", title: "Implementation", description: "Executing priority AI initiatives with measurable milestones and KPIs." },
            { stepId: "05", title: "Training", description: "Upskilling your workforce to manage, operate, and iterate on AI-powered tools." },
            { stepId: "06", title: "Optimization", description: "Continuous review and refinement of your AI strategy based on performance data." }
        ],
        ctaTitle: "Ready for Strategic AI Transformation?",
        ctaSubtitle: "Partner with us to build a comprehensive AI roadmap for your enterprise.",
        ctaButtonText: "Begin Strategy",
        ctaButtonLink: "/contact"
    },
    {
        name: "FaaS Infrastructure",
        slug: "faas-infrastructure",
        description: "Managed infrastructure for AI Agent Framework-as-a-Service, ensuring scalability and peak performance.",
        menuDescription: "Scalable infrastructure for AI agents",
        heroTitle: "FaaS Infrastructure",
        heroSubtitle: ["Powering the future of agentic services."],
        heroTagline: "Infrastructure Excellence",
        featuresTitle: "High-Performance FaaS",
        featuresSubtitle: "Enterprise-grade hosting and orchestration for your agentic fleets.",
        features: [
            { title: "Elastic Scaling", description: "Automatically adjust resources based on agent workload demands.", icon: "Maximize" },
            { title: "Ultra-Low Latency", description: "Global edge deployment for real-time agent responses.", icon: "Zap" },
            { title: "Managed Orchestration", description: "Comprehensive management of agent interactions and state.", icon: "Server" },
            { title: "Observability Hub", description: "Deep visibility into agent performance and resource usage.", icon: "Activity" },
            { title: "Cost Optimization", description: "Efficient compute allocation to reduce infrastructure overhead.", icon: "DollarSign" }
        ],
        problemTitle: "Infrastructure Overload",
        problemSubtitle: "Self-hosting complex agentic frameworks leads to operational friction.",
        problemItems: [
            { title: "Inconsistent Scaling", description: "Agents crashing during peak loads or wasting idle resources." },
            { title: "Maintenance Burden", description: "DevOps teams overwhelmed by patching and updating AI environments." },
            { title: "High Operational Costs", description: "Expensive infrastructure spending without clear ROI visibility." },
            { title: "Performance Degradation", description: "Latency and reliability issues impacting agent response times." }
        ],
        processTitle: "Scaling Your Fleet",
        processSubtitle: "Robust infrastructure from assessment to ongoing support.",
        processSteps: [
            { stepId: "01", title: "Assessment", description: "Evaluating your current infrastructure, workload patterns, and scaling requirements." },
            { stepId: "02", title: "Provisioning", description: "Setting up dedicated compute, memory, and GPU environments for your agents." },
            { stepId: "03", title: "Integration", description: "Connecting your agent frameworks to our FaaS API with secure authentication." },
            { stepId: "04", title: "Migration", description: "Seamlessly moving existing workloads to the new infrastructure with zero downtime." },
            { stepId: "05", title: "Optimization", description: "Fine-tuning resource allocation, auto-scaling rules, and cost efficiency." },
            { stepId: "06", title: "Monitoring", description: "24/7 observability, alerting, and proactive performance management." }
        ],
        ctaTitle: "Ready to Scale Your Agent Fleet?",
        ctaSubtitle: "Get enterprise-grade infrastructure for your agentic AI systems.",
        ctaButtonText: "Scale Now",
        ctaButtonLink: "/contact"
    },
    {
        name: "Tailored Solutions",
        slug: "tailored-solutions",
        description: "Bespoke AI systems built from the ground up to solve your unique operational challenges and industry needs.",
        menuDescription: "Bespoke AI systems for unique needs",
        heroTitle: "Tailored Solutions",
        heroSubtitle: ["Custom AI built for your specific challenges."],
        heroTagline: "Bespoke Development",
        featuresTitle: "Customized Capability",
        featuresSubtitle: "Unique solutions for unique problems.",
        features: [
            { title: "Vertical Specialization", description: "Deep industry-specific knowledge built into every model.", icon: "Briefcase" },
            { title: "Proprietary Models", description: "Custom fine-tuning on your sensitive, proprietary datasets.", icon: "Database" },
            { title: "White-Label Delivery", description: "Seamlessly integrate custom AI as a core feature of your product.", icon: "Tag" },
            { title: "Hybrid Deployment", description: "Cloud, on-premise, or edge deployment options available.", icon: "Box" },
            { title: "Ongoing Evolution", description: "Long-term partnership to iterate and expand system capabilities.", icon: "RefreshCw" }
        ],
        problemTitle: "One-Size-Fits-None",
        problemSubtitle: "Off-the-shelf AI tools often fail to capture industry nuances.",
        problemItems: [
            { title: "Generic Output", description: "AI that doesn't understand your specific business jargon or logic." },
            { title: "Data Privacy Gaps", description: "Inability to use standard tools with restricted datasets." },
            { title: "Limited Integration", description: "Out-of-the-box solutions that don't fit your existing workflows." },
            { title: "Inflexible Customization", description: "Expensive and time-consuming modifications for specific needs." }
        ],
        processTitle: "Crafting Your Solution",
        processSubtitle: "Precision engineering from start to finish.",
        processSteps: [
            { stepId: "01", title: "Consultation", description: "Deep dive into your problem space, data landscape, and success criteria." },
            { stepId: "02", title: "Design", description: "Architecting a solution blueprint with data flows, model selection, and integration points." },
            { stepId: "03", title: "Prototyping", description: "Rapid MVP development to validate the AI hypothesis with real data." },
            { stepId: "04", title: "Development", description: "Full-scale model training, fine-tuning, and application engineering." },
            { stepId: "05", title: "Deployment", description: "Production launch with cloud, on-premise, or hybrid infrastructure." },
            { stepId: "06", title: "Iteration", description: "Continuous feedback loops, model retraining, and feature expansion." }
        ],
        ctaTitle: "Ready for a Tailored AI Solution?",
        ctaSubtitle: "Let us craft an AI system built specifically for your operational needs.",
        ctaButtonText: "Get Started",
        ctaButtonLink: "/contact"
    },
];

const arabicServices = [
    {
        name: "تكامل الذكاء الاصطناعي الوكيل",
        slug: "agentic-ai-integration",
        description: "دمج الوكلاء المستقلين بسلاسة في سير عملك لأتمتة عمليات اتخاذ القرار المعقدة.",
        menuDescription: "وكلاء مستقلون لسير العمل المعقد",
        heroTitle: "تكامل الذكاء الاصطناعي الوكيل",
        heroSubtitle: ["تحويل سير العمل بالذكاء المستقل."],
        heroTagline: "أتمتة الجيل القادم",
        featuresTitle: "لماذا تختار الذكاء الاصطناعي الوكيل؟",
        featuresSubtitle: "تم تصميم وكلائنا للتعامل مع البيئات عالية المخاطر بدقة.",
        features: [
            { title: "اتخاذ قرار مستقل", description: "يمكن للوكلاء تقييم متغيرات متعددة واختيار أفضل مسار للعمل دون تدخل بشري.", icon: "Cpu" },
            { title: "تكامل شامل", description: "اتصال مباشر بمجموعة البرامج الحالية لديك عبر API أو RPA.", icon: "Layers" },
            { title: "عمل على مدار الساعة", description: "عمال أذكياء لا ينامون أبدًا، مما يضمن إنتاجية ثابتة على مدار الساعة.", icon: "Clock" },
            { title: "تعلم تكيفي", description: "أنظمة تحسين ذاتي تعمل على تحسين أدائها بناءً على حلقات التغذية الراجعة.", icon: "Zap" },
            { title: "بنية تحتية آمنة", description: "مبنية ببروتوكولات أمان على مستوى المؤسسات لحماية البيانات الحساسة.", icon: "Shield" }
        ],
        problemTitle: "فجوة الإنتاجية",
        problemSubtitle: "الأتمتة التقليدية جامدة. تتطلب الأعمال الحديثة القابلية للتكيف.",
        problemItems: [
            { title: "اختناقات الأنظمة القديمة", description: "البيانات المعزولة والعمليات اليدوية التي تبطئ النمو." },
            { title: "تكاليف القرار المعقدة", description: "عبء بشري مرتفع للمهام التحليلية المتكررة والمعقدة." },
            { title: "بطء السرعة", description: "المشاريع المتوقفة بسبب انتظار الموافقات اليدوية والتحويلات." },
            { title: "الخطأ البشري", description: "الأخطاء المكلفة التي تمر عبر الإجازات والتعقيد." }
        ],
        processTitle: "عملية التكامل لدينا",
        processSubtitle: "مسار منظم نحو التميز الوكيلي.",
        processSteps: [
            { stepId: "01", title: "الاكتشاف", description: "نحلل سير عملك الحالي لتحديد أعلى فرص الأتمتة عائدًا على الاستثمار." },
            { stepId: "02", title: "الهندسة المعمارية", description: "تصميم إطار عمل وكيلي مخصص يتناسب مع بيئة بياناتك." },
            { stepId: "03", title: "التطوير", description: "بناء وتدريب وكلاء الذكاء الاصطناعي ببياناتك الخاصة ومنطق أعمالك." },
            { stepId: "04", title: "التكامل", description: "ربط الوكلاء بأنظمتك الحالية عبر واجهات برمجة التطبيقات وأتمتة العمليات." },
            { stepId: "05", title: "النشر", description: "طرح تدريجي مع مراقبة مستمرة وضبط دقيق لجاهزية الإنتاج." },
            { stepId: "06", title: "الدعم", description: "صيانة مستمرة وتحسين الأداء وتطوير الوكلاء مع نمو احتياجاتك." }
        ],
        ctaTitle: "هل أنت مستعد لتكامل الذكاء الاصطناعي الوكيل؟",
        ctaSubtitle: "دع فريقنا يصمم استراتيجية وكلاء مستقلين مخصصة لمؤسستك.",
        ctaButtonText: "ابدأ التكامل",
        ctaButtonLink: "/contact"
    },
    {
        name: "استراتيجية المؤسسة",
        slug: "enterprise-strategy",
        description: "خرائط طريق للذكاء الاصطناعي مصممة لتتماشى مع أهداف عملك وتدفع التحول الرقمي طويل الأمد.",
        menuDescription: "خرائط طريق استراتيجية لنمو الأعمال",
        heroTitle: "استراتيجية المؤسسة",
        heroSubtitle: ["تخطيط استراتيجي للتميز المدفوع بالذكاء الاصطناعي."],
        heroTagline: "استشارات استراتيجية",
        featuresTitle: "الأسس الاستراتيجية",
        featuresSubtitle: "بناء مستقبل الذكاء الاصطناعي لمؤسستك على أسس صلبة.",
        features: [
            { title: "خارطة طريق تركز على العائد", description: "إعطاء الأولوية لمبادرات الذكاء الاصطناعي التي تقدم قيمة تجارية ملموسة.", icon: "TrendingUp" },
            { title: "تخفيف المخاطر", description: "تحديد وإدارة مخاطر تنفيذ الذكاء الاصطناعي بشكل استباقي.", icon: "ShieldAlert" },
            { title: "إدارة التغيير", description: "إعداد القوى العاملة لديك للانتقال إلى سير عمل معزز بالذكاء الاصطناعي.", icon: "Users" },
            { title: "نماذج الحوكمة", description: "وضع مبادئ توجيهية أخلاقية وتشغيلية لاستخدام الذكاء الاصطناعي.", icon: "Scale" },
            { title: "اختيار التكنولوجيا", description: "توجيه الخبراء في اختيار نماذج اللغات الكبيرة (LLMs) والمنصات المناسبة.", icon: "Search" }
        ],
        problemTitle: "تبني الذكاء الاصطناعي بلا اتجاه",
        problemSubtitle: "بدون استراتيجية، غالبًا ما تصبح مشاريع الذكاء الاصطناعي تجارب مكلفة.",
        problemItems: [
            { title: "ابتكار مجزأ", description: "أقسام مختلفة تختبر أدوات مختلفة بدون رؤية موحدة." },
            { title: "مخاطر الامتثال", description: "نشر الذكاء الاصطناعي بدون حواجز قانونية أو أخلاقية مناسبة." },
            { title: "هدر الموارد", description: "الميزانية التي يتم إنفاقها على مشاريع تجريبية لا تصل أبدًا إلى الإنتاج." },
            { title: "فجوات المهارات", description: "الفرق التي تفتقر إلى الخبرة لإدارة وتوسيع مبادرات الذكاء الاصطناعي." }
        ],
        processTitle: "الرحلة الاستراتيجية",
        processSubtitle: "من الرؤية إلى التنفيذ.",
        processSteps: [
            { stepId: "01", title: "التدقيق", description: "مراجعة شاملة للمشهد التقني الحالي ونضج البيانات وأهداف العمل." },
            { stepId: "02", title: "الاستراتيجية", description: "تطوير خارطة طريق للتحول بالذكاء الاصطناعي لمدة 24 شهراً متوافقة مع أولويات أعمالك." },
            { stepId: "03", title: "الحوكمة", description: "وضع المبادئ التوجيهية الأخلاقية وأطر الامتثال والهياكل التنظيمية." },
            { stepId: "04", title: "التنفيذ", description: "تنفيذ مبادرات الذكاء الاصطناعي ذات الأولوية مع معالم قابلة للقياس ومؤشرات أداء." },
            { stepId: "05", title: "التدريب", description: "تطوير مهارات قوتك العاملة لإدارة وتشغيل وتطوير الأدوات المدعومة بالذكاء الاصطناعي." },
            { stepId: "06", title: "التحسين", description: "مراجعة وتحسين مستمر لاستراتيجية الذكاء الاصطناعي بناءً على بيانات الأداء." }
        ],
        ctaTitle: "هل أنت مستعد للتحول الاستراتيجي بالذكاء الاصطناعي؟",
        ctaSubtitle: "تعاون معنا لبناء خارطة طريق شاملة للذكاء الاصطناعي لمؤسستك.",
        ctaButtonText: "ابدأ الاستراتيجية",
        ctaButtonLink: "/contact"
    },
    {
        name: "بنية FaaS التحتية",
        slug: "faas-infrastructure",
        description: "بنية تحتية مدارة لإطار عمل وكلاء الذكاء الاصطناعي كخدمة، مما يضمن القابلية للتوسع والأداء الذروة.",
        menuDescription: "بنية تحتية قابلة للتوسع لوكلاء الذكاء الاصطناعي",
        heroTitle: "بنية FaaS التحتية",
        heroSubtitle: ["تمكين مستقبل الخدمات الوكيلية."],
        heroTagline: "التميز في البنية التحتية",
        featuresTitle: "FaaS عالي الأداء",
        featuresSubtitle: "استضافة وأوركسترا على مستوى المؤسسات لأساطيل وكلائك.",
        features: [
            { title: "توسع مرن", description: "ضبط الموارد تلقائيًا بناءً على متطلبات ضغط عمل الوكيل.", icon: "Maximize" },
            { title: "زمن وصول منخفض للغاية", description: "نشر عالمي للحصول على استجابات فورية من الوكلاء.", icon: "Zap" },
            { title: "أوركسترا مدارة", description: "إدارة شاملة لتفاعلات وحالات الوكلاء.", icon: "Server" },
            { title: "مركز المراقبة", description: "رؤية عميقة لأداء الوكلاء واستخدام الموارد.", icon: "Activity" },
            { title: "تحسين التكلفة", description: "تخصيص فعال للموارد لتقليل نفقات البنية التحتية.", icon: "DollarSign" }
        ],
        problemTitle: "عبء البنية التحتية",
        problemSubtitle: "الاستضافة الذاتية لأطر عمل الوكلاء المعقدة تؤدي إلى احتكاك تشغيلي.",
        problemItems: [
            { title: "توسع غير متسق", description: "تعطل الوكلاء أثناء ذروة الأحمال أو هدر الموارد الخاملة." },
            { title: "عبء الصيانة", description: "فرق DevOps غارقة في التحديثات وتصحيح بيئات الذكاء الاصطناعي." },
            { title: "تكاليف تشغيلية عالية", description: "إنفاق البنية التحتية المكلف بدون رؤية واضحة للعائد على الاستثمار." },
            { title: "تدهور الأداء", description: "مشاكل الكمون والموثوقية التي تؤثر على أوقات استجابة الوكلاء." }
        ],
        processTitle: "توسيع أسطولك",
        processSubtitle: "بنية تحتية قوية من التقييم إلى الدعم المستمر.",
        processSteps: [
            { stepId: "01", title: "التقييم", description: "تقييم بنيتك التحتية الحالية وأنماط العمل ومتطلبات التوسع." },
            { stepId: "02", title: "توفير الموارد", description: "إعداد بيئات الحوسبة والذاكرة ووحدات معالجة الرسومات المخصصة لوكلائك." },
            { stepId: "03", title: "التكامل", description: "ربط أطر عمل وكلائك بواجهة برمجة تطبيقات FaaS مع مصادقة آمنة." },
            { stepId: "04", title: "الترحيل", description: "نقل سلس للأحمال الحالية إلى البنية التحتية الجديدة بدون توقف." },
            { stepId: "05", title: "التحسين", description: "ضبط تخصيص الموارد وقواعد التوسع التلقائي وكفاءة التكلفة." },
            { stepId: "06", title: "المراقبة", description: "مراقبة على مدار الساعة وتنبيهات وإدارة أداء استباقية." }
        ],
        ctaTitle: "هل أنت مستعد لتوسيع أسطول وكلائك؟",
        ctaSubtitle: "احصل على بنية تحتية على مستوى المؤسسات لأنظمة الذكاء الاصطناعي الوكيلية.",
        ctaButtonText: "وسّع الآن",
        ctaButtonLink: "/contact"
    },
    {
        name: "حلول مخصصة",
        slug: "tailored-solutions",
        description: "أنظمة ذكاء اصطناعي مفصلة تم بناؤها من الصفر لحل تحدياتك التشغيلية الفريدة واحتياجاتك الصناعية.",
        menuDescription: "أنظمة ذكاء اصطناعي مفصلة لاحتياجات فريدة",
        heroTitle: "حلول مخصصة",
        heroSubtitle: ["ذكاء اصطناعي مخصص مبني لتحدياتك الخاصة."],
        heroTagline: "تطوير مفصل",
        featuresTitle: "قدرة مخصصة",
        featuresSubtitle: "حلول فريدة لمشاكل فريدة.",
        features: [
            { title: "تخصص قطاعي", description: "معرفة صناعية عميقة مدمجة في كل نموذج.", icon: "Briefcase" },
            { title: "نماذج ملكية", description: "ضبط دقيق مخصص على مجموعات بياناتك الحساسة والخاصة.", icon: "Database" },
            { title: "تسليم البطاقة البيضاء (White-Label)", description: "دمج الذكاء الاصطناعي المخصص كميزة أساسية لمنتجك.", icon: "Tag" },
            { title: "نشر هجين", description: "خيارات نشر سحابي، أو في الموقع، أو عند الحافة.", icon: "Box" },
            { title: "تطور مستمر", description: "شراكة طويلة الأمد لتكرار وتوسيع قدرات النظام.", icon: "RefreshCw" }
        ],
        problemTitle: "مقاس واحد لا يناسب الجميع",
        problemSubtitle: "غالبًا ما تفشل أدوات الذكاء الاصطناعي الجاهزة في التقاط الفروق الدقيقة في الصناعة.",
        problemItems: [
            { title: "مخرجات عامة", description: "ذكاء اصطناعي لا يفهم المصطلحات أو المنطق الخاص بشركتك." },
            { title: "فجوات خصوصية البيانات", description: "عدم القدرة على استخدام الأدوات القياسية مع مجموعات البيانات المقيدة." },
            { title: "التكامل المحدود", description: "الحلول الجاهزة التي لا تناسب سير عملك الموجود." },
            { title: "التخصيص غير المرن", description: "التعديلات المكلفة والمستهلكة للوقت لتلبية احتياجات معينة." }
        ],
        processTitle: "صياغة حلك",
        processSubtitle: "هندسة دقيقة من البداية إلى النهاية.",
        processSteps: [
            { stepId: "01", title: "الاستشارة", description: "غوص عميق في مجال مشكلتك ومشهد البيانات ومعايير النجاح." },
            { stepId: "02", title: "التصميم", description: "بناء مخطط الحل مع تدفقات البيانات واختيار النماذج ونقاط التكامل." },
            { stepId: "03", title: "النماذج الأولية", description: "تطوير سريع للنماذج الأولية للتحقق من فرضية الذكاء الاصطناعي ببيانات حقيقية." },
            { stepId: "04", title: "التطوير", description: "تدريب النماذج على نطاق كامل وضبطها الدقيق وهندسة التطبيقات." },
            { stepId: "05", title: "النشر", description: "إطلاق الإنتاج على بنية تحتية سحابية أو محلية أو هجينة." },
            { stepId: "06", title: "التكرار", description: "حلقات تغذية راجعة مستمرة وإعادة تدريب النماذج وتوسيع الميزات." }
        ],
        ctaTitle: "هل أنت مستعد لحل ذكاء اصطناعي مخصص؟",
        ctaSubtitle: "دعنا نصنع نظام ذكاء اصطناعي مبني خصيصًا لاحتياجاتك التشغيلية.",
        ctaButtonText: "ابدأ الآن",
        ctaButtonLink: "/contact"
    }
];

const productsEn = [
    {
        _id: "product-erp",
        orderRank: 1,
        name: "ERP",
        slug: { _type: "slug", current: "erp" },
        description: "Voice-activated ERP system for SMEs. Manage your entire business operation through natural voice commands with AI-powered automation.",
        menuDescription: "Voice-activated ERP for SMEs with AI-powered automation.",
        icon: "/products/erp.svg",
        heroSubtitle: ["Voice-Activated ERP for Modern Business. AI-powered business commands."],
        heroCenterIcon: "/products/voiceerp.svg",
        heroCenterIconAlt: "Voice ERP System Icon",
        heroDemoVideo: "/fasih-demo.mp4",
        heroTagline: "Operational Intelligence",
        exploreButton: "Explore Solution",
        missionTitle: "Voice-First Enterprise Operations",
        missionSubtitle: "Manage your entire business operations through natural voice commands while ensuring security and compliance.",
        missionCards: [
            { _key: "mc-1", title: "Voice-First Interface", description: "Control all ERP functions through natural voice commands, making business management accessible and efficient for everyone." },
            { _key: "mc-2", title: "AI-Powered Automation", description: "Intelligent automation handles routine tasks, data entry, and reporting, freeing your team to focus on strategic decisions." },
            { _key: "mc-3", title: "SME-Optimized Design", description: "Built specifically for small and medium enterprises with scalable architecture that grows with your business needs." },
        ],
        automationTitle: "Smart Automation",
        automationSubtitle: "Streamlining operations from inventory to finance.",
        automationFeatures: [
            { _key: "af-1", title: "Adaptive Legacy Bridge", description: "Seamlessly wraps around your existing systems to enable smart AI improvements without disrupting your current operations." },
            { _key: "af-2", title: "Voice Command Suite", description: "Full voice control of inventory, sales, accounting, and HR management with natural language processing." },
            { _key: "af-3", title: "Real-Time Analytics", description: "Get instant insights into your business performance with AI-powered analytics and predictive reporting." },
            { _key: "af-4", title: "Smart Workflow Automation", description: "Automate complex business processes with intelligent workflows that adapt to your operational patterns." },
        ],
        youtubeVideoId: "oAuaVWvw0lM",
        youtubeVideoTitle: "Voice ERP System in Action",
        performanceMetrics: [
            { _key: "pm-1", value: "75%", label: "Time Savings" },
            { _key: "pm-2", value: "90%", label: "User Satisfaction" },
            { _key: "pm-3", value: "3x", label: "Productivity Increase" },
        ],
        aceternityTitle: "Core ERP Features",
        aceternitySubtitle: "Powerful capabilities for modern businesses.",
        aceternityFeatures: [
            { _key: "ae-1", title: "Business Operations Tracking", description: "Track and manage your business operations with ease using the intuitive ERP interface.", className: "col-span-1 lg:col-span-4 border-b lg:border-r dark:border-neutral-800" },
            { _key: "ae-2", title: "AI Insights Capture", description: "Capture business insights effortlessly using advanced AI technology and analytics.", className: "border-b col-span-1 lg:col-span-2 dark:border-neutral-800" },
            { _key: "ae-3", title: "See ERP in Action", description: "See how the voice-activated ERP system transforms business operations.", className: "col-span-1 lg:col-span-3 lg:border-r dark:border-neutral-800" },
            { _key: "ae-4", title: "Global Deployment", description: "Deploy ERP across multiple locations with our cloud-based architecture and global reach.", className: "col-span-1 lg:col-span-3 border-b lg:border-none" },
        ],
        outcomesTitle: "Outcomes",
        outcomesBadge: "Proof",
        demoTitle: "Voice ERP in Action",
        demoSubtitle: "Watch how voice commands transform business operations.",
        demoBadge: "Demo",
        architectureTitle: "Architecture Deck",
        architectureBadge: "Visual Index",
        architectureSubtitle: "Architecture — ERP. Detailed visualization of the voice-activated ERP engine components.",
        architectureReelImages: ["/productimages/Slide-22.png", "/productimages/Slide-23.png", "/productimages/Slide-24.png"],
        ctaTitle: "Ready to Try ERP?",
        ctaSubtitle: "Manage your entire business through voice commands.",
        ctaButtonText: "Get Started",
        challengesBadge: "Pain Points",
        challengesTitlePart1: "Current Market ",
        challengesTitlePart2: "Challenges",
        challengesSubtitle: "Uncovering operational bottlenecks and manual process inefficiencies that hold SMEs back from scaling efficiently.",
        cinematicNarrative: {
            introLine: "Every day, teams hit the same walls.",
            problemsIntroLine: "Three barriers stand in the way.",
            epiphanyPreLine: "Then everything changes.",
            solutionIntroLine: "Here's how we fix it.",
            recapLine: "You've seen the problems and our solution. Now see it in action.",
        },
        cinematicProblems: [
            { _key: "cp-1", title: "Manual Data Entry Bottleneck", description: "Teams waste hours on forms and spreadsheets instead of running the business.", solTitle: "Voice-First Interface", solDesc: "Control all ERP functions through natural voice commands, making business management accessible and efficient for everyone.", solImpact: "+75% Time Savings" },
            { _key: "cp-2", title: "Siloed Systems", description: "Inventory, sales, and finance don't talk—errors and delays multiply.", solTitle: "AI-Powered Automation", solDesc: "Intelligent automation handles routine tasks, data entry, and reporting, freeing your team to focus on strategic decisions.", solImpact: "Zero Downtime" },
            { _key: "cp-3", title: "Complex Training Overhead", description: "Valuable minds spent on learning legacy UIs instead of driving growth.", solTitle: "SME-Optimized Design", solDesc: "Built specifically for small and medium enterprises with scalable architecture that grows with your business needs.", solImpact: "3x Productivity" },
        ],
        journeyTitle: "Intelligent ERP",
        journeySubtitle: "Voice-first enterprise management with parallel processing.",
        journeyBadge: "Architecture",
        journeyStages: ["Stage One", "Stage Two", "Stage Three"],
        journeyLayers: [
            { _key: "jl-1", title: "Input Management", nodes: ["Voice Input", "Intent NLU", "ERP Manual", "External API"] },
            { _key: "jl-2", title: "Core Engine (Matrix)", nodes: ["Task Planner", "Business Logic", "Execution", "Compliance"] },
            { _key: "jl-3", title: "Global Distribution", nodes: ["Database", "Cloud Sync", "Command Center"] },
        ],
    },
    {
        _id: "product-ai-framework",
        orderRank: 2,
        name: "AI Framework",
        slug: { _type: "slug", current: "ai-framework" },
        description: "A comprehensive AI Agent & Automation Framework designed to build, deploy, and scale intelligent enterprise solutions at unprecedented speed.",
        menuDescription: "Build and deploy AI agents at enterprise scale.",
        icon: "/products/ai-framework.svg",
        heroSubtitle: ["Build powerful AI agents. Scalable enterprise solutions."],
        heroCenterIcon: "/products/ai-framework.svg",
        heroCenterIconAlt: "AI Framework Icon",
        heroDemoVideo: "/fasih-demo.mp4",
        heroTagline: "Agent Orchestration",
        exploreButton: "Explore Solution",
        missionTitle: "Decentralized Intelligence Network",
        missionSubtitle: "Build and deploy AI agents rapidly at enterprise scale with industry-standard reliability.",
        missionCards: [
            { _key: "mc-1", title: "Modular Architecture", description: "Flexible, composable components that adapt to your specific needs, enabling rapid development and customization." },
            { _key: "mc-2", title: "Seamless Integration", description: "Connect seamlessly with existing systems, APIs, and third-party services through standardized interfaces and connectors." },
            { _key: "mc-3", title: "Scalable Design", description: "Built to handle enterprise-scale workloads with high performance, reliability, and automatic scaling capabilities." },
        ],
        automationTitle: "Automation Capabilities",
        automationSubtitle: "Advanced workflows with intuitive tooling.",
        automationFeatures: [
            { _key: "af-1", title: "Agent Orchestration", description: "Coordinate multiple AI agents to work together on complex tasks with intelligent task distribution and collaboration." },
            { _key: "af-2", title: "Workflow Builder", description: "Visual tools to design and deploy automation workflows without coding, with drag-and-drop simplicity." },
            { _key: "af-3", title: "Event-Driven Architecture", description: "React to system events and trigger automated responses in real-time." },
            { _key: "af-4", title: "Monitoring & Analytics", description: "Track performance, debug issues, and optimize your automation workflows with comprehensive monitoring tools." },
        ],
        youtubeVideoId: "oAuaVWvw0lM",
        youtubeVideoTitle: "AI Framework in Action",
        performanceMetrics: [
            { _key: "pm-1", value: "90%", label: "Developer Satisfaction" },
            { _key: "pm-2", value: "10x", label: "Faster Development" },
            { _key: "pm-3", value: "99.9%", label: "Uptime" },
        ],
        aceternityTitle: "Framework Capabilities",
        aceternitySubtitle: "Features for building intelligent systems.",
        aceternityFeatures: [
            { _key: "ae-1", title: "Build AI Agents", description: "Create sophisticated AI agents with our intuitive framework and comprehensive tooling library.", className: "col-span-1 lg:col-span-4 border-b lg:border-r border-white-opacity-20" },
            { _key: "ae-2", title: "Workflow Automation", description: "Design and deploy complex automation workflows with visual tools and drag-and-drop simplicity.", className: "border-b col-span-1 lg:col-span-2 border-white-opacity-20" },
            { _key: "ae-3", title: "See Framework Demo", description: "See how the AI Framework enables rapid development and deployment of enterprise AI solutions.", className: "col-span-1 lg:col-span-3 lg:border-r border-white-opacity-20" },
            { _key: "ae-4", title: "Enterprise Scale", description: "Deploy and scale AI solutions across enterprise infrastructure with high performance and reliability.", className: "col-span-1 lg:col-span-3 border-b lg:border-none" },
        ],
        outcomesTitle: "Outcomes",
        outcomesBadge: "Proof",
        demoTitle: "Framework in Action",
        demoSubtitle: "See rapid AI agent deployment at enterprise scale.",
        demoBadge: "Demo",
        architectureTitle: "Architecture Deck",
        architectureBadge: "Visual Index",
        architectureSubtitle: "Architecture — AI Framework. Detailed visualization of the agent orchestration engine components.",
        architectureReelImages: ["/productimages/Slide-22.png", "/productimages/Slide-23.png", "/productimages/Slide-24.png"],
        ctaTitle: "Ready to Try AI Framework?",
        ctaSubtitle: "Build and deploy AI agents at enterprise scale.",
        ctaButtonText: "Get Started",
        challengesBadge: "Pain Points",
        challengesTitlePart1: "Current Market ",
        challengesTitlePart2: "Challenges",
        challengesSubtitle: "Confronting the slow development cycles and integration barriers that prevent enterprises from deploying AI agents at scale.",
        cinematicNarrative: {
            introLine: "Building AI agents shouldn't take months.",
            problemsIntroLine: "Three obstacles slow you down.",
            epiphanyPreLine: "Then everything changes.",
            solutionIntroLine: "Here's how we fix it.",
            recapLine: "You've seen the problems and our solution. Now see it in action.",
        },
        cinematicProblems: [
            { _key: "cp-1", title: "Slow Development Cycles", description: "Months to build and deploy a single AI agent. Market moves faster.", solTitle: "Modular Architecture", solDesc: "Flexible, composable components that adapt to your specific needs and use cases, enabling rapid development and customization.", solImpact: "10x Faster Dev" },
            { _key: "cp-2", title: "Integration Nightmares", description: "Existing systems and APIs don't plug in—custom glue code everywhere.", solTitle: "Easy Integration", solDesc: "Seamlessly connect with existing systems, APIs, and third-party services through standardized interfaces and connectors.", solImpact: "99.9% Uptime" },
            { _key: "cp-3", title: "Scale Anxiety", description: "Agents work in dev; fall over when traffic hits production.", solTitle: "Scalable Design", solDesc: "Built to handle enterprise-scale workloads with high performance, reliability, and automatic scaling capabilities.", solImpact: "90% Dev Satisfaction" },
        ],
        journeyTitle: "AI Framework Ecosystem",
        journeySubtitle: "A decentralized network powering enterprise-grade intelligence.",
        journeyBadge: "Architecture",
        journeyStages: ["Stage One", "Stage Two", "Stage Three"],
        journeyLayers: [
            { _key: "jl-1", title: "AI Application Layer", nodes: ["Web3 Chatbot", "Crypto Alerts", "AI Agents"] },
            { _key: "jl-2", title: "$CGPT Token Layer", nodes: ["Governance", "$CGPT Utility", "Staking"] },
            { _key: "jl-3", title: "AI Framework Blockchain", nodes: ["Validators", "Framework Core", "Data Market", "SDK", "GPU Market"] },
        ],
    },
    {
        _id: "product-zakra",
        orderRank: 3,
        name: "Zakra",
        slug: { _type: "slug", current: "zakra" },
        description: "Smart Knowledge Agent that delivers instant, context-aware answers from your entire knowledge base. Unlock the power of your enterprise data.",
        menuDescription: "Smart knowledge agent for instant answers.",
        icon: "/products/zakra.svg",
        heroSubtitle: ["Smart Knowledge Management. Actionable insights from your data."],
        heroCenterIcon: "/products/zakra.svg",
        heroCenterIconAlt: "Zakra Knowledge Agent Icon",
        heroDemoVideo: "/fasih-demo.mp4",
        heroTagline: "Knowledge Synthesis",
        exploreButton: "Explore Solution",
        missionTitle: "Unified Knowledge Intelligence",
        missionSubtitle: "Instant, context-aware answers from your entire knowledge base. Make information accessible.",
        missionCards: [
            { _key: "mc-1", title: "Intelligent Search", description: "Natural language queries that understand context and intent, delivering precise answers from your knowledge base." },
            { _key: "mc-2", title: "Multi-Source Integration", description: "Connect and search across documents, databases, wikis, and knowledge repositories in one unified interface." },
            { _key: "mc-3", title: "Context-Aware Responses", description: "Get answers that understand your specific domain, industry terminology, and organizational context." },
        ],
        automationTitle: "Knowledge Capabilities",
        automationSubtitle: "Intelligent and effortless knowledge management.",
        automationFeatures: [
            { _key: "af-1", title: "Semantic Search", description: "Search for information using meaning, not just keywords. Understands synonyms, related concepts, and context." },
            { _key: "af-2", title: "Knowledge Graphing", description: "Visualize connections between concepts, documents, and people to discover hidden relationships in your data." },
            { _key: "af-3", title: "Automatic Summarization", description: "Generate concise summaries of lengthy documents, meetings, and reports to save time and improve comprehension." },
            { _key: "af-4", title: "Real-Time Updates", description: "Stay current with automatic indexing of new content and notifications about changes to relevant information." },
        ],
        youtubeVideoId: "oAuaVWvw0lM",
        youtubeVideoTitle: "Zakra Knowledge Agent Demo",
        performanceMetrics: [
            { _key: "pm-1", value: "80%", label: "Faster Information Retrieval" },
            { _key: "pm-2", value: "95%", label: "Answer Accuracy" },
            { _key: "pm-3", value: "60%", label: "Time Saved" },
        ],
        aceternityTitle: "Zakra Features",
        aceternitySubtitle: "Intelligent knowledge management solutions.",
        aceternityFeatures: [
            { _key: "ae-1", title: "Smart Knowledge Search", description: "Search across your entire knowledge base with natural language queries and semantic understanding.", className: "col-span-1 lg:col-span-4 border-b lg:border-r border-white-opacity-20" },
            { _key: "ae-2", title: "Knowledge Graph Visualization", description: "Visualize connections between concepts, documents, and people in your knowledge base.", className: "border-b col-span-1 lg:col-span-2 border-white-opacity-20" },
            { _key: "ae-3", title: "See Zakra in Action", description: "See how Zakra transforms information retrieval and knowledge management for your organization.", className: "col-span-1 lg:col-span-3 lg:border-r border-white-opacity-20" },
            { _key: "ae-4", title: "Multi-Source Integration", description: "Connect and search across documents, databases, wikis, and knowledge repositories seamlessly.", className: "col-span-1 lg:col-span-3 border-b lg:border-none" },
        ],
        outcomesTitle: "Outcomes",
        outcomesBadge: "Proof",
        demoTitle: "Knowledge in Action",
        demoSubtitle: "Watch instant answers flow from your knowledge base.",
        demoBadge: "Demo",
        architectureTitle: "Architecture Deck",
        architectureBadge: "Visual Index",
        architectureSubtitle: "Architecture — Zakra. Detailed visualization of the knowledge synthesis engine components.",
        architectureReelImages: ["/productimages/Slide-22.png", "/productimages/Slide-23.png", "/productimages/Slide-24.png"],
        ctaTitle: "Ready to Try Zakra?",
        ctaSubtitle: "Unlock instant, context-aware answers from your knowledge base.",
        ctaButtonText: "Get Started",
        challengesBadge: "Pain Points",
        challengesTitlePart1: "Current Market ",
        challengesTitlePart2: "Challenges",
        challengesSubtitle: "Exposing the knowledge silos and retrieval gaps that keep enterprises from leveraging their own data effectively.",
        cinematicNarrative: {
            introLine: "Knowledge is scattered. Answers are hard to find.",
            problemsIntroLine: "Three barriers stand in the way.",
            epiphanyPreLine: "Then everything changes.",
            solutionIntroLine: "Here's how we fix it.",
            recapLine: "You've seen the problems and our solution. Now see it in action.",
        },
        cinematicProblems: [
            { _key: "cp-1", title: "Information Scattered Everywhere", description: "Docs, Excel, wikis—no single place to get a reliable answer.", solTitle: "Intelligent Search", solDesc: "Natural language queries that understand context and intent, delivering precise answers from your knowledge base.", solImpact: "80% Faster Retrieval" },
            { _key: "cp-2", title: "Manual Tagging and Indexing", description: "Content grows faster than your team can organize it.", solTitle: "Multi-Source Integration", solDesc: "Connect and search across documents, databases, wikis, and knowledge repositories in one unified interface.", solImpact: "95% Answer Accuracy" },
            { _key: "cp-3", title: "Generic Search Results", description: "Keyword matches that miss context and domain nuance.", solTitle: "Context-Aware Responses", solDesc: "Get answers that understand your specific domain, industry terminology, and organizational context.", solImpact: "60% Time Saved" },
        ],
        journeyTitle: "Zakra Knowledge",
        journeySubtitle: "Unified data intelligence through centralized graph hub.",
        journeyBadge: "Architecture",
        journeyStages: ["Stage One", "Stage Two", "Stage Three"],
        journeyLayers: [
            { _key: "jl-1", title: "Intake Network", nodes: ["Documents", "Databases", "Cloud Wiki", "Intake Hub"] },
            { _key: "jl-2", title: "Knowledge Core (Hub)", nodes: ["Graph Central", "Entity Sync", "Semantic Index", "Access Control", "Cache"] },
            { _key: "jl-3", title: "Intelligence Delivery", nodes: ["User Query", "Context AI", "Smart Answer"] },
        ],
    },
    {
        _id: "product-jawib",
        orderRank: 4,
        name: "Jawib",
        slug: { _type: "slug", current: "jawib" },
        description: "Intelligent Customer Service Agent providing 24/7 personalized support. Transform your customer experience with seamless, human-like interactions.",
        menuDescription: "24/7 AI customer service agent.",
        icon: "/products/jawib.svg",
        heroSubtitle: ["Intelligent 24/7 support. Exceptional customer experiences."],
        heroCenterIcon: "/products/jawib.svg",
        heroCenterIconAlt: "Jawib Customer Service Agent Icon",
        heroDemoVideo: "/fasih-demo.mp4",
        heroTagline: "Service Automation",
        exploreButton: "Explore Solution",
        missionTitle: "Automated Support Solution",
        missionSubtitle: "Intelligent Customer Service Agent providing 24/7 personalized support. Improve satisfaction and scale operations.",
        missionCards: [
            { _key: "mc-1", title: "24/7 Availability", description: "Provide instant support to customers anytime, anywhere, with intelligent responses that never sleep." },
            { _key: "mc-2", title: "Multi-Channel Support", description: "Engage customers across chat, email, phone, and social media with consistent, personalized experiences." },
            { _key: "mc-3", title: "Human Handoff", description: "Seamlessly escalate complex issues to human agents when needed, with full context and conversation history." },
        ],
        automationTitle: "Service Features",
        automationSubtitle: "Transforming customer interactions.",
        automationFeatures: [
            { _key: "af-1", title: "Natural Language Understanding", description: "Understand customer intent, sentiment, and context to provide accurate, helpful responses in natural conversation." },
            { _key: "af-2", title: "Ticket Management", description: "Automatically create, prioritize, and track support tickets while maintaining detailed conversation records." },
            { _key: "af-3", title: "Knowledge Base Integration", description: "Access your product documentation, FAQs, and knowledge base to provide accurate, up-to-date information." },
            { _key: "af-4", title: "Analytics & Insights", description: "Track customer satisfaction, identify common issues, and gain insights to continuously improve your service." },
        ],
        youtubeVideoId: "oAuaVWvw0lM",
        youtubeVideoTitle: "Jawib Customer Service Agent Demo",
        performanceMetrics: [
            { _key: "pm-1", value: "90%", label: "First Contact Resolution" },
            { _key: "pm-2", value: "2s", label: "Average Response Time" },
            { _key: "pm-3", value: "4.8/5", label: "Customer Satisfaction" },
        ],
        aceternityTitle: "Jawib Features",
        aceternitySubtitle: "Solutions for exceptional service.",
        aceternityFeatures: [
            { _key: "ae-1", title: "24/7 Customer Support", description: "Provide intelligent, instant customer support around the clock with natural language understanding.", className: "col-span-1 lg:col-span-4 border-b lg:border-r border-white-opacity-20" },
            { _key: "ae-2", title: "Multi-Channel Engagement", description: "Engage customers across chat, email, phone, and social media with consistent experiences.", className: "border-b col-span-1 lg:col-span-2 border-white-opacity-20" },
            { _key: "ae-3", title: "See Jawib Demo", description: "See how Jawib transforms customer service with AI-powered automation.", className: "col-span-1 lg:col-span-3 lg:border-r border-white-opacity-20" },
            { _key: "ae-4", title: "Global Support Network", description: "Scale customer service operations globally with multi-language support and regional deployment.", className: "col-span-1 lg:col-span-3 border-b lg:border-none" },
        ],
        outcomesTitle: "Outcomes",
        outcomesBadge: "Proof",
        demoTitle: "Support in Action",
        demoSubtitle: "See 24/7 AI customer service handle real requests.",
        demoBadge: "Demo",
        architectureTitle: "Architecture Deck",
        architectureBadge: "Visual Index",
        architectureSubtitle: "Architecture — Jawib. Detailed visualization of the customer service automation engine components.",
        architectureReelImages: ["/productimages/Slide-22.png", "/productimages/Slide-23.png", "/productimages/Slide-24.png"],
        ctaTitle: "Ready to Try Jawib?",
        ctaSubtitle: "Transform your customer service with 24/7 AI support.",
        ctaButtonText: "Get Started",
        challengesBadge: "Pain Points",
        challengesTitlePart1: "Current Market ",
        challengesTitlePart2: "Challenges",
        challengesSubtitle: "Addressing the support volume overload and inconsistent service quality that erode customer trust and drain support teams.",
        cinematicNarrative: {
            introLine: "Support volume never stops. Teams burn out.",
            problemsIntroLine: "Three barriers stand in the way.",
            epiphanyPreLine: "Then everything changes.",
            solutionIntroLine: "Here's how we fix it.",
            recapLine: "You've seen the problems and our solution. Now see it in action.",
        },
        cinematicProblems: [
            { _key: "cp-1", title: "Support Volume Overload", description: "Tickets pile up. Customers wait. Teams burn out.", solTitle: "24/7 Availability", solDesc: "Provide instant support to customers anytime, anywhere, with intelligent responses that never sleep.", solImpact: "90% First Contact" },
            { _key: "cp-2", title: "Inconsistent Answers", description: "Different agents, different scripts—customers get mixed messages.", solTitle: "Multi-Channel Support", solDesc: "Engage customers across chat, email, phone, and social media with consistent, personalized experiences.", solImpact: "2s Response Time" },
            { _key: "cp-3", title: "Handoff Friction", description: "When bots can't help, context is lost and customers repeat themselves.", solTitle: "Human Handoff", solDesc: "Seamlessly escalate complex issues to human agents when needed, with full context and conversation history.", solImpact: "4.8/5 Satisfaction" },
        ],
        journeyTitle: "Jawib Support",
        journeySubtitle: "Automated triage and resolution tree.",
        journeyBadge: "Architecture",
        journeyStages: ["Stage One", "Stage Two", "Stage Three"],
        journeyLayers: [
            { _key: "jl-1", title: "Omnichannel Entry", nodes: ["Unified Inbox"] },
            { _key: "jl-2", title: "Triage & Pathing", nodes: ["Smart Router", "AI Resolution", "Human Escalation"] },
            { _key: "jl-3", title: "Feedback Loop", nodes: ["Intent Scan", "Model Update", "Knowledge Sync"] },
        ],
    },
    {
        _id: "product-fasih",
        orderRank: 5,
        name: "Fasih",
        slug: { _type: "slug", current: "fasih" },
        description: "The native Arabic LLM bridging the gap with deep understanding of dialects and cultural nuances for precise, regionally-aware processing.",
        menuDescription: "Native Arabic LLM with dialect support.",
        icon: "/products/fasih.svg",
        heroSubtitle: ["Native Arabic AI. Built to understand Arabic."],
        heroCenterIcon: "/products/fasih.svg",
        heroCenterIconAlt: "Fasih Arabic LLM Icon",
        heroDemoVideo: "/fasih-demo.mp4",
        heroTagline: "Cultural Nuance",
        exploreButton: "Explore Solution",
        missionTitle: "Precise Arabic Understanding",
        missionSubtitle: "Bridge the gap with deep understanding of dialects and cultural nuances for precise, regionally-aware processing.",
        missionCards: [
            { _key: "mc-1", title: "Native Arabic Understanding", description: "Deep understanding of Modern Standard Arabic, regional dialects, and cultural nuances for accurate communication." },
            { _key: "mc-2", title: "Cultural Context", description: "Trained on Arabic content with cultural awareness, ensuring appropriate and contextually relevant responses." },
            { _key: "mc-3", title: "Multi-Dialect Support", description: "Recognize and process various Arabic dialects while maintaining high accuracy across different regions." },
        ],
        automationTitle: "Arabic Capabilities",
        automationSubtitle: "Arabic language processing and generation.",
        automationFeatures: [
            { _key: "af-1", title: "Text Generation", description: "Generate high-quality Arabic text for content creation, translations, and automated responses with natural fluency." },
            { _key: "af-2", title: "Language Understanding", description: "Deep semantic understanding of Arabic text, including complex grammar, idiomatic expressions, and regional variations." },
            { _key: "af-3", title: "Translation Services", description: "Accurate bidirectional translation between Arabic and other languages while preserving context." },
            { _key: "af-4", title: "Voice & Speech", description: "Arabic speech recognition and text-to-speech support with natural pronunciation and intonation." },
        ],
        youtubeVideoId: "oAuaVWvw0lM",
        youtubeVideoTitle: "Fasih Arabic LLM Overview",
        performanceMetrics: [
            { _key: "pm-1", value: "98%", label: "Arabic Text Accuracy" },
            { _key: "pm-2", value: "15", label: "Dialects Supported" },
            { _key: "pm-3", value: "50B+", label: "Arabic Tokens Trained" },
        ],
        aceternityTitle: "Fasih Features",
        aceternitySubtitle: "A leading native Arabic language model.",
        aceternityFeatures: [
            { _key: "ae-1", title: "Native Arabic Processing", description: "Deep understanding of Modern Standard Arabic, regional dialects, and cultural nuances for accurate communication.", className: "col-span-1 lg:col-span-4 border-b lg:border-r border-white-opacity-20" },
            { _key: "ae-2", title: "Multi-Dialect Support", description: "Recognize and process various Arabic dialects with high accuracy across different regions.", className: "border-b col-span-1 lg:col-span-2 border-white-opacity-20" },
            { _key: "ae-3", title: "See Fasih Overview", description: "See how Fasih delivers precise, culturally-aware Arabic language processing for your applications.", className: "col-span-1 lg:col-span-3 lg:border-r border-white-opacity-20" },
            { _key: "ae-4", title: "Global Arabic Support", description: "Deploy Arabic language capabilities across global applications with regional dialect support.", className: "col-span-1 lg:col-span-3 border-b lg:border-none" },
        ],
        outcomesTitle: "Outcomes",
        outcomesBadge: "Proof",
        demoTitle: "Arabic Intelligence in Action",
        demoSubtitle: "Experience native Arabic understanding across dialects.",
        demoBadge: "Demo",
        architectureTitle: "Architecture Deck",
        architectureBadge: "Visual Index",
        architectureSubtitle: "Architecture — Fasih. Detailed visualization of the native Arabic language model components.",
        architectureReelImages: ["/productimages/Slide-22.png", "/productimages/Slide-23.png", "/productimages/Slide-24.png"],
        ctaTitle: "Ready to Try Fasih?",
        ctaSubtitle: "Experience native Arabic language understanding.",
        ctaButtonText: "Get Started",
        challengesBadge: "Pain Points",
        challengesTitlePart1: "Current Market ",
        challengesTitlePart2: "Challenges",
        challengesSubtitle: "Revealing the dialect blindness and cultural gaps in generic language models that fail Arabic-speaking users and markets.",
        cinematicNarrative: {
            introLine: "Arabic deserves more than an afterthought.",
            problemsIntroLine: "Three barriers stand in the way.",
            epiphanyPreLine: "Then everything changes.",
            solutionIntroLine: "Here's how we fix it.",
            recapLine: "You've seen the problems and our solution. Now see it in action.",
        },
        cinematicProblems: [
            { _key: "cp-1", title: "Arabic Lost in Translation", description: "Generic models treat Arabic as an afterthought—dialects and nuance get flattened.", solTitle: "Native Arabic Understanding", solDesc: "Deep understanding of Modern Standard Arabic, regional dialects, and cultural nuances for accurate communication.", solImpact: "98% Text Accuracy" },
            { _key: "cp-2", title: "Cultural Context Missing", description: "Outputs that are technically correct but tone-deaf to region and culture.", solTitle: "Cultural Context", solDesc: "Trained on Arabic content with cultural awareness, ensuring appropriate and contextually relevant responses.", solImpact: "15 Dialects" },
            { _key: "cp-3", title: "One-Size-Fits-All Dialects", description: "MSA-only support leaves regional users and content out in the cold.", solTitle: "Multi-Dialect Support", solDesc: "Recognize and process various Arabic dialects while maintaining high accuracy across different regions.", solImpact: "50B+ Tokens" },
        ],
        journeyTitle: "Fasih Arabic LLM",
        journeySubtitle: "Sequential processing pipeline.",
        journeyBadge: "Architecture",
        journeyStages: ["Stage One", "Stage Two", "Stage Three"],
        journeyLayers: [
            { _key: "jl-1", title: "Input Pre-processing", nodes: ["Text Input", "Tokenizer", "Dialect ID"] },
            { _key: "jl-2", title: "Neural Core", nodes: ["Arabic LLM"] },
            { _key: "jl-3", title: "Generation Pipeline", nodes: ["Generation", "Compliance Audit", "Final Output"] },
        ],
    },
];

async function seed() {
    console.log("🚀 Starting Sanity seed...");

    try {
        // 0. Seed Home Page (en)
        console.log("📄 Creating Home Page (en)...");
        await client.createOrReplace({
            _id: "homePage-en",
            _type: "homePage",
            language: "en",
            heroTitle: "AI-Powered Solutions / For Modern Enterprises",
            heroSubtitle: "Transform your business with intelligent automation, voice-activated systems, and AI agents that drive productivity and innovation",
            heroBadgePill: "Exclusive",
            heroBadgeDescription: "Tomorrow's Edge, Built Today",
            servicesTitle: "Focus on Growth",
            servicesSubtitle: "Explore our comprehensive suite of AI solutions designed to transform your enterprise.",
            servicesBadge: "Our Solutions",
            services: [
                { _key: "svc-agentic", id: "agentic", title: "Agentic AI Integration", description: "Seamlessly integrate autonomous agents into your workflow to automate complex decision-making processes.", image: "/bentogird/agenticai.svg" },
                { _key: "svc-strategy", id: "strategy", title: "Enterprise Strategy", description: "Tailored AI roadmaps designed to align with your business goals and drive long-term digital transformation.", image: "/bentogird/enterprise.svg" },
                { _key: "svc-faas", id: "faas", title: "FaaS Infrastructure", description: "Managed infrastructure for AI Agent Framework-as-a-Service, ensuring scalability and peak performance.", image: "/bentogird/faas.svg" },
                { _key: "svc-tailored", id: "tailored", title: "Tailored Solutions", description: "Bespoke AI systems built from the ground up to solve your unique operational challenges and industry needs.", image: "/bentogird/tailored.svg" },
            ],
            achievementsTitle: "Our Impact",
            achievementsSubtitle: "Key metrics that define our success.",
            achievementsBadge: "Our Achievement",
            achievements: [
                { _key: "ach-1", number: "99.9%", label: "System Reliability", isHighlighted: false },
                { _key: "ach-2", number: "50K+", label: "Active AI Agents", isHighlighted: true },
                { _key: "ach-3", number: "75%", label: "Efficiency Gain", isHighlighted: false },
            ],
            missionTitle: "Our Mission",
            missionSubtitle: "Experience the dual power of autonomous execution and deep analytical insight, engineered for the future of enterprise.",
            missionBadge: "Our Mission",
            missionCards: [
                { _key: "mc-1", title: "Autonomous Execution", description: "Deploy intelligent workers that handle complex workflows 24/7 without supervision.", image: "/mission/execution.svg" },
                { _key: "mc-2", title: "Analytical Insight", description: "Transform raw data into actionable foresight with our advanced neural models.", image: "/mission/insight.svg" },
            ],
            technologyTitle: "Our Technology Excellence",
            technologySubtitle: "Experience the dual power of autonomous execution and deep analytical insight, engineered for the future of enterprise.",
            technologyBadge: "Core Tech",
            technologyCards: [
                { _key: "tc-1", title: "Autonomous Agents", description: "Deploy intelligent workers that handle complex workflows 24/7 without supervision.", image: "/tech/agents.svg" },
                { _key: "tc-2", title: "Neural Processing", description: "Transform raw data into actionable foresight with our advanced neural models.", image: "/tech/neural.svg" },
            ],
            partners: [
                { _key: "p-1", logo: "/partners/anthropic.svg", alt: "Anthropic" },
                { _key: "p-2", logo: "/partners/openai.svg", alt: "OpenAI" },
            ],
            ctaTitle: "Ready to Transform Your Business?",
            ctaSubtitle: "Join hundreds of enterprises leveraging AI-powered automation to drive growth, efficiency, and innovation.",
            ctaButtonText: "Start Building Now",
            ctaButtonHref: "/contact",
            textRevealContent: "Forging the intelligence layer of tomorrow. Unlocking limitless potential.",
        });

        // 1. Seed About Page (en)
        console.log("📄 Creating About Page (en)...");
        await client.createOrReplace({
            _id: "aboutPage-en",
            _type: "aboutPage",
            language: "en",
            heroTitle: "Our Legacy",
            heroSubtitle: "Building the foundation for enterprise intelligence. From humble beginnings to global infrastructure — this is our story.",
            heroBadge: "Legacy & Vision",
            heroTitlePart1: "Our ",
            heroTitlePart2: "Legacy",
            teamMembers: [
                { _key: "tm-1", name: "Alex Morgan", role: "CEO & Founder", bio: "Visionary leader with over 15 years of experience in AI and strategic planning. Passionate about ethical AI development.", image: "https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=800&auto=format&fit=crop" },
                { _key: "tm-2", name: "Sarah Chen", role: "CTO", bio: "Expert in machine learning and neural networks. Leads the technical vision and engineering teams at ESAP AI.", image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=800&auto=format&fit=crop" },
                { _key: "tm-3", name: "Marcus Johnson", role: "Head of Product", bio: "Product strategist focused on user-centric design and scalable solutions. Formerly at major tech giants.", image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=800&auto=format&fit=crop" },
                { _key: "tm-4", name: "Emily Rodriguez", role: "Lead Designer", bio: "Award-winning designer creating intuitive and beautiful interfaces. Believes in design as a storytelling medium.", image: "https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=800&auto=format&fit=crop" },
                { _key: "tm-5", name: "David Kim", role: "Senior AI Engineer", bio: "Specializes in NLP and large language models. Contributor to several open-source AI projects.", image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=800&auto=format&fit=crop" },
                { _key: "tm-6", name: "Lisa Wang", role: "Marketing Director", bio: "Creative marketer with a knack for viral campaigns and brand building in the tech sector.", image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=800&auto=format&fit=crop" },
                { _key: "tm-7", name: "James Wilson", role: "DevOps Engineer", bio: "Infrastructure expert ensuring smooth deployment and high availability for AI systems.", image: "https://images.unsplash.com/photo-1519345182560-3f2917c472ef?q=80&w=800&auto=format&fit=crop" },
                { _key: "tm-8", name: "Robert Chen", role: "Frontend Developer", bio: "Passionate about creating responsive, accessible, and high-performance user interfaces.", image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=800&auto=format&fit=crop" },
                { _key: "tm-9", name: "Sofia Martinez", role: "AI Ethics Researcher", bio: "Committed to ensuring fairness, transparency, and accountability in AI algorithms.", image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=800&auto=format&fit=crop" },
            ],
            narrativeDesignation: "Designation",
            teamCategoryLabel: "CORE TEAM MEMBER",
            teamLeadershipLabel: "LEADERSHIP",
            teamInnovationLabel: "INNOVATION",
            historyTitle: "The Journey of ESAP AI",
            historyBadge: "Our Legacy",
            historySubtitle: "From complex manual workflows to enterprise-grade AI autonomy.",
            historyHook: "Digitalizing what can't be digitalized — a real case study.",
            historyPhases: [
                {
                    _key: "hp-1",
                    year: "2020",
                    phaseLabel: "Phase 1",
                    title: "The build",
                    description: "Around late 2020, a well-known consulting company in construction — mostly government projects — was running everything on Excel and physical papers: project management, HR, finance, supplier management. They had tried Dynamics 365, Odoo; none fit their complicated business logic. So they went hybrid until 2020, when money loss, poor tracking, and manual effort made it clear: something had to be done. I entered the scene. One month to show one workflow. I almost quit. Then a senior employee said: here you can build something from scratch, something big. I stayed. I became an employee inside a struggling module, learning paper flow and approvals by observation — no requirements, no docs. One month, 24/7, and I built a prototype. We shook hands. I spent the next 8 months going deep: data in Excel everywhere, 60k+ records, owner-defined formats, workflow that had to match exactly. I decided they would love it and use it without complaining — no training, obvious UI, simple pending tasks. We built 6–7 key modules. Within two weeks the owner migrated everything to production.",
                    highlight: "80% paperwork gone. No manual tracking. Finally, relief.",
                },
                {
                    _key: "hp-2",
                    year: "2021",
                    phaseLabel: "Phase 2",
                    title: "Migration & automation",
                    description: "Migration was brutal. Excel data was messy: missing references, wrong grouping, broken structure. We built a pipeline — what can be synced, what can't; restructure what's possible; store the rest as extra sources. We learned why companies fear digitalizing: millions of messy records are not easy. Automation became a huge advantage. We built automations that were unheard of back then: attendance (letters, tickets, objections, payroll deductions), expense (employees always knew where and how much they spent). Many more automations helped scale without extra manpower. After migration and automation, the owner decided to open a software solution company. Almost every company suffers with outdated ERPs or fears digitalizing due to complexity, time, cost, and disaster outcomes. Our real advantage: understanding core issues and the end-user.",
                    highlight: "",
                },
                {
                    _key: "hp-3",
                    year: "2022",
                    phaseLabel: "Phase 3",
                    title: "AI & redefining",
                    description: "AI started emerging strongly around 2022. Agents started being discussed. We saw the potential beyond automation and started building next-gen AI products for enterprises. Goal: enterprise AI solutions based on deep end-user understanding, constant feedback from departments, and strict end-user satisfaction rules. Big companies do agentic automation and process intelligence, but most don't care about end-users. That's where ESAP AI comes in. ESAP's main goal: intelligent agents — AGI-like workplace agents. Not LLMs alone; architecture and orchestration are the key. Aligned with Vision 2030: from Saudi Arabia to the world.",
                    highlight: "",
                },
            ],
            visionTitle: "Our vision",
            visionBody: "A complete enterprise ecosystem operated by intelligent agents. Every employee has an AI agent that assists them. Employees do not need to learn ERP systems, understand workflows, or remember how things are operated. They provide the required data and review before submission. Everything else — forms, navigation, tracking, approvals, workflows, execution — is handled by the agent. The agent is the executor. We're building the framework that makes this possible: complete enterprise architecture, agents that orchestrate any business logic dynamically, full CRUD and ERP actions, and the ability to adapt to different companies, workflows, and industries. This is just the beginning.",
        });

        // 1. Seed English Products (with new fields)
        console.log("📦 Creating Products (en)...");
        for (const product of productsEn) {
            await client.createOrReplace({
                ...product,
                _type: "productDocument",
                language: "en",
            });
            console.log(`   ✓ ${product.name}`);
        }

        // 2. Seed English Services
        for (const service of services) {
            console.log(`  Creating service: ${service.name} (en)...`);
            await client.createOrReplace({
                _id: `service-${service.slug}`,
                _type: "serviceDocument",
                language: "en",
                name: service.name,
                slug: { _type: "slug", current: service.slug },
                description: service.description,
                menuDescription: service.menuDescription,
                heroTitle: service.heroTitle,
                heroSubtitle: service.heroSubtitle,
                heroTagline: service.heroTagline,
                featuresTitle: service.featuresTitle,
                featuresSubtitle: service.featuresSubtitle,
                featuresBadge: "What we deliver",
                featuresCentralNode: "Core Service",
                features: service.features,
                problemTitle: service.problemTitle,
                problemSubtitle: service.problemSubtitle,
                problemBadge: "The Challenge",
                problemItems: service.problemItems,
                processTitle: service.processTitle,
                processSubtitle: service.processSubtitle,
                processBadge: "Process",
                processSteps: service.processSteps,
                portalVideoTitle: "Video Portal",
                portalVideoDescription: "Watch how our solution transforms your workflow",
                beforeAfterLabel: "Before & after",
                beforeAfterTitle: "See the difference",
                ctaTitle: service.ctaTitle,
                ctaSubtitle: service.ctaSubtitle,
                ctaButtonText: service.ctaButtonText,
                ctaButtonLink: service.ctaButtonLink
            });
        }

        // 3. Seed Arabic Services
        for (const service of arabicServices) {
            console.log(`  Creating service: ${service.name} (ar)...`);
            await client.createOrReplace({
                _id: `service-${service.slug}-ar`,
                _type: "serviceDocument",
                language: "ar",
                name: service.name,
                slug: { _type: "slug", current: service.slug },
                description: service.description,
                menuDescription: service.menuDescription,
                heroTitle: service.heroTitle,
                heroSubtitle: service.heroSubtitle,
                heroTagline: service.heroTagline,
                featuresTitle: service.featuresTitle,
                featuresSubtitle: service.featuresSubtitle,
                featuresBadge: "ما نقدمه",
                featuresCentralNode: "الخدمة الأساسية",
                features: service.features,
                problemTitle: service.problemTitle,
                problemSubtitle: service.problemSubtitle,
                problemBadge: "التحدي",
                problemItems: service.problemItems,
                processTitle: service.processTitle,
                processSubtitle: service.processSubtitle,
                processBadge: "العملية",
                processSteps: service.processSteps,
                portalVideoTitle: "بوابة الفيديو",
                portalVideoDescription: "شاهد كيف يحول حلنا سير عملك",
                beforeAfterLabel: "قبل وبعد",
                beforeAfterTitle: "شاهد الفرق",
                ctaTitle: service.ctaTitle,
                ctaSubtitle: service.ctaSubtitle,
                ctaButtonText: service.ctaButtonText,
                ctaButtonLink: service.ctaButtonLink
            });
        }

        console.log("✅ Seed complete!");
    } catch (error) {
        console.error("❌ Seed failed:", error);
        process.exit(1);
    }
}

seed();
